project_name: kubectl-rl-top

before:
  hooks:
    - go mod download
    - go mod tidy

builds:
  - id: kubectl-rltop
    binary: kubectl-rltop
    main: .
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

release:
  github:
    owner: veditoid
    name: kubectl-rl-top
  draft: false
  prerelease: auto
  mode: replace

blobs:
  - provider: github
    owner: veditoid
    name: kubectl-rl-top
    ids:
      - kubectl-rltop-linux-amd64
      - kubectl-rltop-linux-arm64
      - kubectl-rltop-darwin-amd64
      - kubectl-rltop-darwin-arm64
      - kubectl-rltop-windows-amd64

