apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: rltop
  version: {{ .TagName }}
spec:
  version: {{ .TagName }}
  shortDescription: Display pod resource usage with requests and limits
  description: |
    Display pod resource usage (CPU and memory) along with resource requests and limits.
    Works like 'kubectl top pods' but also shows the resource requests and limits
    defined in the pod specifications.
  homepage: https://github.com/vedit/kubectl-rltop
  caveats: |
    Requires metrics-server to be installed in your cluster.
    The plugin needs access to the Metrics API and the core Kubernetes API.
  platforms:
    - selector:
        matchLabels:
          os: darwin
          arch: amd64
      {{addURIAndSha "https://github.com/vedit/kubectl-rltop/releases/download/{{ .TagName }}/kubectl-rltop-darwin-amd64.tar.gz" .TagName | indent 6 }}
      bin: kubectl-rltop
    - selector:
        matchLabels:
          os: darwin
          arch: arm64
      {{addURIAndSha "https://github.com/vedit/kubectl-rltop/releases/download/{{ .TagName }}/kubectl-rltop-darwin-arm64.tar.gz" .TagName | indent 6 }}
      bin: kubectl-rltop
    - selector:
        matchLabels:
          os: linux
          arch: amd64
      {{addURIAndSha "https://github.com/vedit/kubectl-rltop/releases/download/{{ .TagName }}/kubectl-rltop-linux-amd64.tar.gz" .TagName | indent 6 }}
      bin: kubectl-rltop
    - selector:
        matchLabels:
          os: linux
          arch: arm64
      {{addURIAndSha "https://github.com/vedit/kubectl-rltop/releases/download/{{ .TagName }}/kubectl-rltop-linux-arm64.tar.gz" .TagName | indent 6 }}
      bin: kubectl-rltop
    - selector:
        matchLabels:
          os: windows
          arch: amd64
      {{addURIAndSha "https://github.com/vedit/kubectl-rltop/releases/download/{{ .TagName }}/kubectl-rltop-windows-amd64.tar.gz" .TagName | indent 6 }}
      bin: kubectl-rltop.exe
    - selector:
        matchLabels:
          os: windows
          arch: arm64
      {{addURIAndSha "https://github.com/vedit/kubectl-rltop/releases/download/{{ .TagName }}/kubectl-rltop-windows-arm64.tar.gz" .TagName | indent 6 }}
      bin: kubectl-rltop.exe